# Generated by Django 3.1.6 on 2021-05-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
