# Generated by Django 3.1.6 on 2021-05-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
