# Generated by Django 3.1.6 on 2021-05-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0020_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
