# Generated by Django 3.1.6 on 2021-05-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0022_auto_20210526_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
