# Generated by Django 3.1.6 on 2021-05-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0026_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
