# Generated by Django 3.1.6 on 2021-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0029_post_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tacgia',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
