# Generated by Django 3.1.6 on 2021-05-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_auto_20210526_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
