# Generated by Django 3.1.6 on 2021-05-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
